<?php $id = $fetch['candidate_id'];
                            if($id==1){
                                $count=$count1;
                            }
                            if($id==2){
                                $count=$count2;
                            }
                            if($id==3){
                                $count=$count3;
                            }
                            if($id==4){
                                $count=$count4;
                            }
                            if($id==5){
                                $count=$count5;
                            }
                            if($id==6){
                                $count=$count6;
                            }
                            elseif($id==7){
                                $count=$count7;
                            }
                            elseif($id==8){
                                $count=$count8;
                            }
                            elseif($id==9){
                                $count=$count9;
                            }
                            elseif($id==10){
                                $count=$count10;
                            }
                            elseif($id==11){
                                $count=$count11;
                            }
                            elseif($id==12){
                                $count=$count12;
                            }
                            elseif($id==13){
                                $count=$count13;
                            }
                            elseif($id==14){
                                $count=$count14;
                            }
                            elseif($id==14){
                                $count=$count14;
                            }
                            elseif($id==15){
                                $count=$count15;
                            }


                            elseif($id==16){
                                $count=$count16;
                            }
                            elseif($id==17){
                                $count=$count17;
                            }
                            elseif($id==18){
                                $count=$count18;
                            }
                            elseif($id==19){
                                $count=$count19;
                            }
                            elseif($id==20){
                                $count=$count20;
                            }
                            elseif($id==21){
                                $count=$count21;
                            }
                            elseif($id==22){
                                $count=$count22;
                            }
                            elseif($id==23){
                                $count=$count23;
                            }
                            elseif($id==24){
                                $count=$count24;
                            }
                            
                            
                            else{
                                $count=0;
                            }
                            ?>